### ISSUE TITLE
config.json is constant overwritten

### ISSUE THREAD

**Issue by treecamp** [kmlucy/docker-assistant-relay#1]
Hi there!

I got your container running, and it's working good. Problem that i have is that my config.json is constant overwritten with the default settings.

I mapped the file to my docker folder:
docker/assistant-relay/config.json -> /assistant-relay/server/configurations/config.json

Same for the 2 folders btw:
docker/assistant-relay/tokens -> /assistant-relay/server/configurations/tokens
docker/assistant-relay/secrets -> /assistant-relay/server/configurations/secrets

I was trying this because i wanted to change the time, the assistant-relay is running 1 hour behind. Quite annoying with the quiet hours, which i can't change, because the file is being overwritten instantly.

Any idea what's causing this? And how i can solve it?

Cheers,

Coen

**Comment by kmlucy** [comment]
I'm not sure what is causing that. I also volume mount the config.json file, but mine isn't getting overwritten. The only thing I can think of to check is that your config.json permissions are correct such that the container has access to the file. If you are just looking to fix the time offset, just mount the localtime file: ``-v /etc/localtime:/etc/localtime:ro``.

**Comment by treecamp** [comment]
I reinstalled your container, config.json isn't overwritten anymore so that's good. But the time is still off, your localtime trick didn't work. Any other thoughts?

Thanks for the help, much appreciated!

Coen

**Comment by kmlucy** [comment]
Two more possibilities: ``-v /etc/timezone:/etc/timezone:ro`` and ``-e TZ=America/New_York`` (substitute your time zone). I've never found a consistently good way of getting the date correct inside a container. See if one of those does the trick.

**Comment by treecamp** [comment]
Nope, i tried this now:

sudo docker run -d \
    --name assistant-relay -p 3000:3000 \
    -v /volume1/docker/assistant-relay/secrets:/assistant-relay/server/configurations/secrets:ro \
    -v /volume1/docker/assistant-relay/tokens:/assistant-relay/server/configurations/tokens:ro \
    -v /volume1/docker/assistant-relay/config.json:/assistant-relay/server/configurations/config.json \
    -v /etc/localtime:/etc/localtime:ro \
    -e TZ=Europe/Amsterdam \
    kmlucy/docker-assistant-relay

**Comment by kmlucy** [comment]
Should be fixed now, try again with the TZ environment variable. I added the tzdata package to the image and it worked in my testing.

**Comment by treecamp** [comment]
Thanks for all the help sofar, but for some reason it's still not working. 
I tried it like this:

sudo docker run -d \
    --name assistant-relay -p 3000:3000 \
    -v /volume1/docker/assistant-relay/secrets:/assistant-relay/server/configurations/secrets:ro \
    -v /volume1/docker/assistant-relay/tokens:/assistant-relay/server/configurations/tokens:ro \
    -v /volume1/docker/assistant-relay/config.json:/assistant-relay/server/configurations/config.json \
    -e TZ=Europe/Amsterdam \
    kmlucy/docker-assistant-relay

And i tried it again with the local time file like this:
sudo docker run -d \
    --name assistant-relay -p 3000:3000 \
    -v /volume1/docker/assistant-relay/secrets:/assistant-relay/server/configurations/secrets:ro \
    -v /volume1/docker/assistant-relay/tokens:/assistant-relay/server/configurations/tokens:ro \
    -v /volume1/docker/assistant-relay/config.json:/assistant-relay/server/configurations/config.json \
    -v /etc/localtime:/etc/localtime:ro \
    -e TZ=Europe/Amsterdam \
    kmlucy/docker-assistant-relay

Also checked my NAS timezone, that's all fine. 
As soon as the container is up, i check the log and it's an hour behind.

Not sure whats going wrong here.

**Comment by kmlucy** [comment]
I think it must be something with your setup, it works fine on my machine:
```
$ docker run --rm -it -e TZ=Europe/Amsterdam kmlucy/docker-assistant-relay date
Fri Jan 25 20:25:10 CET 2019
```

Are you sure you've pulled the latest version?

**Comment by treecamp** [comment]
I removed the container, and then the image, and re-downloaded it from the registry.

When i use the command i do get the correct time..
$ sudo docker run --rm -it -e TZ=Europe/Amsterdam kmlucy/docker-assistant-relay date
Password: 
Fri Jan 25 20:27:34 CET 2019

But in the container log it's an hour behind, i'll experiment with the quiet hours if it's correct now, i'll let you know.

**Comment by treecamp** [comment]
"start": 23, "end": 21
Dude, chill, it's quiet time!

"start": 23, "end": 20
Dude, chill, it's quiet time!

"start": 23, "end": 19
{"audio":"http://192.168.1.2:3000/audio?v=61","success":true}

Seems to me that it's not correct yet, it should have said something at the 23-20 setting too i guess?

**Comment by kmlucy** [comment]
I would open an issue over in the Assistant Relay repo. The time inside the container is correct, so I'm not sure why the time Assistant Relay uses would be different.

**Comment by treecamp** [comment]
Thank you for the help! I will 👍

**Comment by kmlucy** [comment]
I'm going to close this, but just reopen if it somehow turns out to be an issue with the container.

**Comment by freakshock88** [comment]
I have the issue with config.json being overwritten. There does not seem to be a permissions problem. 
This is my config (docker-compose):

`assistant-relay:
    container_name: assistant-relay
    environment:
      - TZ=Europe/Amsterdam
    image: kmlucy/docker-assistant-relay
    ports:
      - '3001:3000'
    restart: unless-stopped
    volumes:
      - '/volume1/docker/assistant-relay/secrets:/assistant-relay/server/configurations/secrets'
      - '/volume1/docker/assistant-relay/tokens:/assistant-relay/server/configurations/tokens'
      - '/volume1/docker/assistant-relay/config.json:/assistant-relay/server/configurations/config.json'`

I also get an error when starting the container: 
`> assistant-relay@2.1.1 start /assistant-relay
> node server/app.js
Received command broadcast Assistant Relay is now setup and running 
(node:17) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.setUser (/assistant-relay/server/assistant.js:162:24)
    at Promise (/assistant-relay/server/assistant.js:63:30)
    at new Promise (<anonymous>)
    at Object.sendTextInput (/assistant-relay/server/assistant.js:58:12)
    at /assistant-relay/server/assistant.js:50:8
    at /assistant-relay/node_modules/async/dist/async.js:473:16
    at replenish (/assistant-relay/node_modules/async/dist/async.js:1006:25)
    at /assistant-relay/node_modules/async/dist/async.js:1016:9
    at Object.eachOfLimit (/assistant-relay/node_modules/async/dist/async.js:1041:24)
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Assistant Relay is now setup and running for 
You can now visit undefined in a browser, or send POST requests to it`

**Comment by kmlucy** [comment]
I'm not sure what to tell you. It works perfectly on my server. I can share the command I use to start it and the permissions of my files if you like:

```
docker run --rm --name assistant-relay -v /etc/localtime:/etc/localtime:ro -v /opt/assistant-relay/secrets:/assistant-relay/server/configurations/secrets:ro -v /opt/assistant-relay/tokens:/assistant-relay/server/configurations/tokens:ro -v /opt/assistant-relay/config.json:/assistant-relay/server/configurations/config.json kmlucy/docker-assistant-relay
```

Here are the permissions on my host machine. I just changed my username to my id.
```
-rw-r--r-- 1 1000 1000  962 Dec  1 09:06 config.json
drwxr-xr-x 2 1000 1000 4.0K Nov 29  2018 secrets
drwxr-xr-x 2 1000 1000 4.0K Sep 30  2018 tokens


secrets:
total 4.0K
-rw-r--r-- 1 1000 1000 436 Sep 27  2018 kmlucy.json

tokens:
total 4.0K
-rw-r--r-- 1 root root 328 Sep 30  2018 kmlucy-tokens.json
```
